// <auto-generated />
namespace FormApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class dropColumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dropColumn));
        
        string IMigrationMetadata.Id
        {
            get { return "202302102024253_dropColumn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
